### ISSUE TITLE
Fails when CGI 4.11 or later is installed

### ISSUE THREAD

**Issue by andk** [theory/text-markup#10]
As per subject. Since CGI is not declared as direct dependency the cpan testers reports do not show the finding. I verified it by downgrading to LEEJO/CGI-4.10.tar.gz. This made the test pass the failed before the downgrade. Likewise an upgrade of CGI made the test fail where it passed before the upgrade.

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by theory** [comment]
Thank you, @andk, this explains the shitload of failures I saw in my inbox this morning. Will have to make a fix today.

**Comment by theory** [comment]
Uh…the latest CGI.pm is [listed as 4.04](http://search.cpan.org/dist/CGI/) on search.pan.org. Weird. CPAN.pm installed 4.13 on my box. o_O

**Comment by theory** [comment]
MetaCPAN [has 4.13](https://metacpan.org/release/CGI) as the latest release; I've emailed Graham about search.cpan.org.
