### ISSUE TITLE
t/formats.t fails when CGI-4.14 or -4.15 is installed

### ISSUE THREAD

**Issue by andk** [theory/text-markup#15]
As per subject. Downgrading to LEEJO/CGI-4.13.tar.gz is good as a workaround.

Sample fail report:

http://www.cpantesters.org/cpan/report/54465521

(At the time of this writing 4.15 is the newest)

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by theory** [comment]
I believe that 8f292f026ff2362a0c4949a23ddb856ca6abe4c5 fixes this issue.
