### ISSUE TITLE
Please allow (read) access to %REGEX_FOR

### ISSUE THREAD

**Issue by xtaran** [theory/text-markup#17]
Please allow (read) access to `%REGEX_FOR`, either via some accessor method or using `our` instead of `my`.

I'm trying to write a wrapper which uses Text::Markup for both, deciding if a file can be parsed and for saving the result in another file. For the latter, I'd like to replace the suffix matched by Text::Markup to `.html`, but for that I need to know which part of the file name matched

This could be solved by a method which returns either

* the whole hash mapping formats to regular expressions (most flexible)
* the actually used regular expression,
* the matched suffix,
* or the file name with the matched suffix being removed (least flexible).

Just using `our` instead of `my` should suffice, too.

**Comment by theory** [comment]
Happy to add a method to return the whole hash, but can't you find the matched suffix by matching `/[.][^.]+\z/` on the file name?

**Comment by xtaran** [comment]
Thanks for the prompt implementation!

> Happy to add a method to return the whole hash, but can't you find the matched suffix by matching `/[.][^.]+\z/` on the file name?

Yes, that would work in all current cases, but since Text::Markup allows other backends to also add regexps via the `register` method, you can't be sure that they don't contain a dot.

**Comment by theory** [comment]
Oh, I suppose that's true, but if they don't, it kind of violates the spirit of the whole thing.
