### ISSUE TITLE
input from var

### ISSUE THREAD

**Issue by mbaudis** [theory/text-markup#20]
For parsing non-local data, it would make sense to use already extracted file content as input; e.g. passing it as either string or list. Or: adding reading from we based files. (Or do I miss existing capabilities?)

**Comment by theory** [comment]
You don't miss anything; reading a file handle or string is not supported. You'll have to write files to disk, first.

**Comment by cxw42** [comment]
I know you already closed this, but it is a feature I would appreciate as well.  Would you be willing to consider at least reopening this issue in case anyone has time for a PR?
